import type { Metadata } from "next";
import { Figtree } from "next/font/google";

import Providers from "@/components/providers";
import { cn } from "@/lib/utils";
import "./globals.css";

const figTree = Figtree({ subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(figTree.className, "antialiased")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
